services:
  mysql:
    image: mysql:8.4
    container_name: fitnessstudio-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Password123!
      MYSQL_DATABASE: fitness_studio_booking
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: fitnessstudio-redis
    ports:
      - "6379:6379"

volumes:
  mysql-data:
