// <auto-generated />
using System;
using FitnessStudioBooking.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessStudioBooking.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FitnessStudioBooking.Domain.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("BookedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("CreditRefunded")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerPackageId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TimetableScheduleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerPackageId");

                    b.HasIndex("TimetableScheduleId");

                    b.HasIndex("CustomerId", "TimetableScheduleId", "Status");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookedAt = new DateTimeOffset(new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreditRefunded = false,
                            CustomerId = 1,
                            CustomerPackageId = 1,
                            Status = 1,
                            TimetableScheduleId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookedAt = new DateTimeOffset(new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreditRefunded = false,
                            CustomerId = 5,
                            CustomerPackageId = 5,
                            Status = 1,
                            TimetableScheduleId = 1
                        },
                        new
                        {
                            Id = 3,
                            BookedAt = new DateTimeOffset(new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreditRefunded = false,
                            CustomerId = 3,
                            CustomerPackageId = 3,
                            Status = 1,
                            TimetableScheduleId = 10
                        });
                });

            modelBuilder.Entity("FitnessStudioBooking.Domain.Business", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.HasKey("Id");

                    b.ToTable("Businesses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rezerv Fitness"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Downtown Yoga"
                        });
                });

            modelBuilder.Entity("FitnessStudioBooking.Domain.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "customer1@example.com",
                            FullName = "Customer 1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "customer2@example.com",
                            FullName = "Customer 2"
                        },
                        new
                        {
                            Id = 3,
                            Email = "customer3@example.com",
                            FullName = "Customer 3"
                        },
                        new
                        {
                            Id = 4,
                            Email = "customer4@example.com",
                            FullName = "Customer 4"
                        },
                        new
                        {
                            Id = 5,
                            Email = "customer5@example.com",
                            FullName = "Customer 5"
                        },
                        new
                        {
                            Id = 6,
                            Email = "customer6@example.com",
                            FullName = "Customer 6"
                        },
                        new
                        {
                            Id = 7,
                            Email = "customer7@example.com",
                            FullName = "Customer 7"
                        },
                        new
                        {
                            Id = 8,
                            Email = "customer8@example.com",
                            FullName = "Customer 8"
                        },
                        new
                        {
                            Id = 9,
                            Email = "customer9@example.com",
                            FullName = "Customer 9"
                        },
                        new
                        {
                            Id = 10,
                            Email = "customer10@example.com",
                            FullName = "Customer 10"
                        });
                });

            modelBuilder.Entity("FitnessStudioBooking.Domain.CustomerPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RemainingCredits")
                        .HasColumnType("int");

                    b.Property<int>("TotalCredits")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerPackages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusinessId = 1,
                            CustomerId = 1,
                            ExpiryDate = new DateTimeOffset(new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RemainingCredits = 8,
                            TotalCredits = 10
                        },
                        new
                        {
                            Id = 2,
                            BusinessId = 1,
                            CustomerId = 2,
                            ExpiryDate = new DateTimeOffset(new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RemainingCredits = 0,
                            TotalCredits = 5
                        },
                        new
                        {
                            Id = 3,
                            BusinessId = 2,
                            CustomerId = 3,
                            ExpiryDate = new DateTimeOffset(new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RemainingCredits = 10,
                            TotalCredits = 10
                        },
                        new
                        {
                            Id = 4,
                            BusinessId = 1,
                            CustomerId = 4,
                            ExpiryDate = new DateTimeOffset(new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RemainingCredits = 10,
                            TotalCredits = 10
                        },
                        new
                        {
                            Id = 5,
                            BusinessId = 1,
                            CustomerId = 5,
                            ExpiryDate = new DateTimeOffset(new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RemainingCredits = 9,
                            TotalCredits = 10
                        },
                        new
                        {
                            Id = 6,
                            BusinessId = 1,
                            CustomerId = 6,
                            ExpiryDate = new DateTimeOffset(new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RemainingCredits = 10,
                            TotalCredits = 10
                        },
                        new
                        {
                            Id = 7,
                            BusinessId = 1,
                            CustomerId = 7,
                            ExpiryDate = new DateTimeOffset(new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RemainingCredits = 10,
                            TotalCredits = 10
                        },
                        new
                        {
                            Id = 8,
                            BusinessId = 2,
                            CustomerId = 8,
                            ExpiryDate = new DateTimeOffset(new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RemainingCredits = 10,
                            TotalCredits = 10
                        },
                        new
                        {
                            Id = 9,
                            BusinessId = 2,
                            CustomerId = 9,
                            ExpiryDate = new DateTimeOffset(new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RemainingCredits = 10,
                            TotalCredits = 10
                        },
                        new
                        {
                            Id = 10,
                            BusinessId = 1,
                            CustomerId = 10,
                            ExpiryDate = new DateTimeOffset(new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            RemainingCredits = 10,
                            TotalCredits = 10
                        });
                });

            modelBuilder.Entity("FitnessStudioBooking.Domain.TimetableSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableSlots")
                        .HasColumnType("int");

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InstructorName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("TimetableSchedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableSlots = 2,
                            BusinessId = 1,
                            ClassName = "Yoga Class",
                            EndTime = new DateTimeOffset(new DateTime(2026, 7, 11, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            InstructorName = "John Doe",
                            StartTime = new DateTimeOffset(new DateTime(2026, 7, 11, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            AvailableSlots = 5,
                            BusinessId = 1,
                            ClassName = "HIIT",
                            EndTime = new DateTimeOffset(new DateTime(2026, 7, 11, 11, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            InstructorName = "May Lin",
                            StartTime = new DateTimeOffset(new DateTime(2026, 7, 11, 10, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3,
                            AvailableSlots = 1,
                            BusinessId = 1,
                            ClassName = "Pilates",
                            EndTime = new DateTimeOffset(new DateTime(2026, 7, 12, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            InstructorName = "Aung Ko",
                            StartTime = new DateTimeOffset(new DateTime(2026, 7, 12, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 4,
                            AvailableSlots = 3,
                            BusinessId = 2,
                            ClassName = "Hot Yoga",
                            EndTime = new DateTimeOffset(new DateTime(2026, 7, 12, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            InstructorName = "Nora",
                            StartTime = new DateTimeOffset(new DateTime(2026, 7, 12, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 5,
                            AvailableSlots = 4,
                            BusinessId = 2,
                            ClassName = "Stretch",
                            EndTime = new DateTimeOffset(new DateTime(2026, 7, 13, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            InstructorName = "Chris",
                            StartTime = new DateTimeOffset(new DateTime(2026, 7, 13, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 6,
                            AvailableSlots = 2,
                            BusinessId = 1,
                            ClassName = "Spin",
                            EndTime = new DateTimeOffset(new DateTime(2026, 7, 13, 19, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            InstructorName = "David",
                            StartTime = new DateTimeOffset(new DateTime(2026, 7, 13, 18, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 7,
                            AvailableSlots = 8,
                            BusinessId = 1,
                            ClassName = "Boxing",
                            EndTime = new DateTimeOffset(new DateTime(2026, 7, 14, 18, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            InstructorName = "Thiri",
                            StartTime = new DateTimeOffset(new DateTime(2026, 7, 14, 17, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 8,
                            AvailableSlots = 10,
                            BusinessId = 2,
                            ClassName = "Meditation",
                            EndTime = new DateTimeOffset(new DateTime(2026, 7, 14, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            InstructorName = "Zin",
                            StartTime = new DateTimeOffset(new DateTime(2026, 7, 14, 7, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 9,
                            AvailableSlots = 6,
                            BusinessId = 1,
                            ClassName = "Strength",
                            EndTime = new DateTimeOffset(new DateTime(2026, 7, 15, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            InstructorName = "Myo",
                            StartTime = new DateTimeOffset(new DateTime(2026, 7, 15, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 10,
                            AvailableSlots = 1,
                            BusinessId = 2,
                            ClassName = "Flow Yoga",
                            EndTime = new DateTimeOffset(new DateTime(2026, 7, 15, 17, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            InstructorName = "Ei",
                            StartTime = new DateTimeOffset(new DateTime(2026, 7, 15, 16, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("FitnessStudioBooking.Domain.WaitlistEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerPackageId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("PromotedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TimetableScheduleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CustomerPackageId");

                    b.HasIndex("TimetableScheduleId", "Status", "JoinedAt");

                    b.ToTable("WaitlistEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 6,
                            CustomerPackageId = 6,
                            JoinedAt = new DateTimeOffset(new DateTime(2026, 7, 9, 0, 1, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = 1,
                            TimetableScheduleId = 1
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 7,
                            CustomerPackageId = 7,
                            JoinedAt = new DateTimeOffset(new DateTime(2026, 7, 9, 0, 2, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = 1,
                            TimetableScheduleId = 1
                        });
                });

            modelBuilder.Entity("FitnessStudioBooking.Domain.Booking", b =>
                {
                    b.HasOne("FitnessStudioBooking.Domain.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessStudioBooking.Domain.CustomerPackage", "CustomerPackage")
                        .WithMany()
                        .HasForeignKey("CustomerPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessStudioBooking.Domain.TimetableSchedule", "TimetableSchedule")
                        .WithMany("Bookings")
                        .HasForeignKey("TimetableScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("CustomerPackage");

                    b.Navigation("TimetableSchedule");
                });

            modelBuilder.Entity("FitnessStudioBooking.Domain.CustomerPackage", b =>
                {
                    b.HasOne("FitnessStudioBooking.Domain.Business", "Business")
                        .WithMany("Packages")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessStudioBooking.Domain.Customer", "Customer")
                        .WithMany("Packages")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FitnessStudioBooking.Domain.TimetableSchedule", b =>
                {
                    b.HasOne("FitnessStudioBooking.Domain.Business", "Business")
                        .WithMany("TimetableSchedules")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("FitnessStudioBooking.Domain.WaitlistEntry", b =>
                {
                    b.HasOne("FitnessStudioBooking.Domain.Customer", "Customer")
                        .WithMany("WaitlistEntries")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessStudioBooking.Domain.CustomerPackage", "CustomerPackage")
                        .WithMany()
                        .HasForeignKey("CustomerPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessStudioBooking.Domain.TimetableSchedule", "TimetableSchedule")
                        .WithMany("WaitlistEntries")
                        .HasForeignKey("TimetableScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("CustomerPackage");

                    b.Navigation("TimetableSchedule");
                });

            modelBuilder.Entity("FitnessStudioBooking.Domain.Business", b =>
                {
                    b.Navigation("Packages");

                    b.Navigation("TimetableSchedules");
                });

            modelBuilder.Entity("FitnessStudioBooking.Domain.Customer", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Packages");

                    b.Navigation("WaitlistEntries");
                });

            modelBuilder.Entity("FitnessStudioBooking.Domain.TimetableSchedule", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("WaitlistEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
